// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDncoecOO_JHY7vPJ7NKk8Qxf_zy-0xASA',
    appId: '1:895136376523:web:23e40101076078c79cdd4e',
    messagingSenderId: '895136376523',
    projectId: 'movieapp-4cdd9',
    authDomain: 'movieapp-4cdd9.firebaseapp.com',
    storageBucket: 'movieapp-4cdd9.firebasestorage.app',
    measurementId: 'G-B928T1K67G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFBaNbtesL3UUyHe25AhQusSRXjUvtfa4',
    appId: '1:895136376523:android:03b195ece5363f399cdd4e',
    messagingSenderId: '895136376523',
    projectId: 'movieapp-4cdd9',
    storageBucket: 'movieapp-4cdd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvh11pGRN702RKJawPlOb48JR-2Nc5uf8',
    appId: '1:895136376523:ios:addc14cc23ec1c289cdd4e',
    messagingSenderId: '895136376523',
    projectId: 'movieapp-4cdd9',
    storageBucket: 'movieapp-4cdd9.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvh11pGRN702RKJawPlOb48JR-2Nc5uf8',
    appId: '1:895136376523:ios:addc14cc23ec1c289cdd4e',
    messagingSenderId: '895136376523',
    projectId: 'movieapp-4cdd9',
    storageBucket: 'movieapp-4cdd9.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDncoecOO_JHY7vPJ7NKk8Qxf_zy-0xASA',
    appId: '1:895136376523:web:23e40101076078c79cdd4e',
    messagingSenderId: '895136376523',
    projectId: 'movieapp-4cdd9',
    authDomain: 'movieapp-4cdd9.firebaseapp.com',
    storageBucket: 'movieapp-4cdd9.firebasestorage.app',
    measurementId: 'G-B928T1K67G',
  );

}